# Site settings
title: BAE-Cigarettes
email: ecig@example.com
description: > # this means to ignore newlines until "baseurl:"
  Your E-Cigeratte Source in Argentina!
baseurl: "http://ryan258.github.io/ecargentina" # the subpath of your site, e.g. /blog/
url: "http://ryan258.github.io/ecargentina" # the base hostname & protocol for your site
twitter_username: 
github_username:
facebook_pagename: 
ganalytics_UA: 

# Build settings
markdown: kramdown
