# Site settings
title: Mensajeriama Argentina
email: mensajeriama@example.com
description: > # this means to ignore newlines until "baseurl:"
  Your E-Cigeratte Source in Argentina!
baseurl: "http://ryan258.github.io/mensajeriama" # the subpath of your site, e.g. /blog/
url: "http://ryan258.github.io/mensajeriama" # the base hostname & protocol for your site
twitter_username: 
github_username:
facebook_pagename: 
ganalytics_UA: 

# Build settings
markdown: kramdown
